# Generated by Django 4.2.5 on 2023-10-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='user',
        ),
    ]
