# Generated by Django 4.2.5 on 2023-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_directmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='thread_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
