# Generated by Django 4.2.5 on 2023-10-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_directmessage_thread_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
