# Generated by Django 4.2.5 on 2023-11-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_reciever_directmessage_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_name', models.CharField(blank=True, max_length=200, null=True)),
                ('id_accepted', models.BooleanField(default=True)),
            ],
        ),
    ]
