# Generated by Django 4.2.5 on 2023-09-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_customuser_is_varified_customuser_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
